name: intl_translation_xliff
description: Extract messages to a xliff file and generate translations from xliff files
version: 1.0.0
homepage: https://github.com/jamesblasco/intl_translation_format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl_translation_format:
    git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_format
      ref: null_safe #it-0.0.3
  xml: ^5.1.2

dev_dependencies:
  test: ^1.15.0
  analyzer: '>=0.36.0 <2.8.0'
  args: '>=0.12.1 <2.3.0'
  dart_style: ^2.1.1
  intl: '>=0.15.3 <=0.17.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=4.0.0 < 4.4.0'
  pedantic: ^1.8.0
