name: intl_translation_xliff
description: Extract messages to a xliff file and generate translations from xliff files
version: 1.0.0
homepage: https://github.com/jamesblasco/intl_translation_format
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  intl_translation_format:
    # path: /Users/stpu/Documents/work/extlibs/intl_translation_format/intl_translation_format
    git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_format
      ref: stefan_update-for-lingohub-changes-feb-2023
  xml: ^6.0.0

dev_dependencies:
  test: ^1.15.0
  analyzer: ^5.0.0
  args: '>=0.12.1 <2.4.0'
  dart_style: ^2.1.1
  intl: '>=0.15.3 <=0.18.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: ^5.0.0
  flutter_lints: ^2.0.1
