name: util
description: s


environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
 

dev_dependencies:
   derry: 


scripts:
  # General generate
  generate:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart  --output-dir lib/l10n/ --project-name intl_messages
  g-json:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/json/intl_messages_en.json lib/l10n/json/intl_messages_es.json --output-dir lib/l10n/ --project-name intl_messages --format json
  g-arb:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/arb/intl_messages_en.arb lib/l10n/arb/intl_messages_es.arb --output-dir lib/l10n/ --project-name intl_messages --format arb
  g-multi-json:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/multi_json/intl_messages_multi.json --output-dir lib/l10n/ --format multi_language_json --project-name intl_messages
  g-xliff:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/xliff/intl_messages_en.xliff lib/l10n/xliff/intl_messages_es.xliff --output-dir lib/l10n/ --project-name intl_messages --format xliff-2
  g-strings:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/strings/intl_messages_en.strings lib/l10n/strings/intl_messages_es.strings --output-dir lib/l10n/ --project-name intl_messages --format strings
  g-po:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/gettext/intl_messages_en.po lib/l10n/gettext/intl_messages_es.po --output-dir lib/l10n/ --project-name intl_messages --format po
  g-mo:
    execution: once 
    scripts: 
     - cd intl_translation_example
     - flutter pub run intl_translation_format:generate lib/main.dart lib/l10n/gettext/intl_messages_en.mo lib/l10n/gettext/intl_messages_es.mo --output-dir lib/l10n/ --project-name intl_messages --format mo
  

   # General extract
  extract:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/ --project-name intl_messages
  e-json:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/json/ --project-name intl_messages --format json
  e-arb:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/arb/ --project-name intl_messages --format arb
  e-multi-json:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/multi_json/ --project-name intl_messages_multi --format multi_language_json
  e-xliff:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/xliff/ --project-name intl_messages --format xliff-2
  e-strings:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/strings/ --project-name intl_messages --format strings
  e-po:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/gettext/ --project-name intl_messages --format po
  e-mo:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_format:extract lib/main.dart --locale en --output-dir lib/l10n/gettext/ --project-name intl_messages --format mo
  e-all:
    - $e-json
    - $e-arb
    - $e-multi-json
    - $e-xliff
  
  
  
  # Json commands
  generate-json:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_json:generate_from_json lib/main.dart lib/l10n/intl_messages_en.json lib/l10n/intl_messages_es.json --output-dir lib/l10n/
  extract-json:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_json:extract_to_json lib/main.dart --locale en --output-dir lib/l10n/ --output-file intl_messages_en.json
  generate-multi-json:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_multi_language_json:generate_from_multi_language_json lib/main.dart lib/l10n/intl_messages.json --output-dir lib/l10n/
  extract-multi-json:
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_multi_language_json:extract_to_multi_language_json lib/main.dart --locale en --output-dir lib/l10n/ --output-file intl_messages_multi_template.json
  generate-arb: 
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_arb:generate_from_arb lib/main.dart lib/l10n/intl_messages_en.arb lib/l10n/intl_messages_es.arb --output-dir lib/l10n/
  extract-arb: 
    execution: once 
    scripts:
     - cd intl_translation_example
     - flutter pub run intl_translation_arb:extract_to_arb lib/main.dart --locale en --output-dir lib/l10n/ --output-file intl_messages_en.json
  petit: 
    execution: once 
    scripts:
     - cd intl_translation_xliff
     - dart ./bin/petit_parser.dart

