dart:
  - dev

stages:
  - analyze_and_format:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - command: pub run build_runner test --delete-conflicting-outputs -- -P presubmit
      os:
        - linux
        - windows

cache:
  directories:
    - .dart_tool/build        