name: intl_translation_format
description: This package provides multiformat support for the Intl package
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl_translation:
    git:
      url: https://github.com/dart-lang/intl_translation/
  intl_translation_arb:
    path: '../arb'
  intl_translation_json:
    path: '../experimental/intl_translation_json'  
  intl_translation_xliff:
    path: '../xliff'  
  intl_translation_strings:
    path: '../experimental/intl_translation_strings'    
  intl_translation_gettext:
    path: '../experimental/intl_translation_gettext'    
  yaml: ^2.2.1  
dev_dependencies:
  test: ^1.15.1
  analyzer: '>=0.36.0 <0.40.0'
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  intl: '>=0.15.3 <0.17.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=1.1.3 < 3.0.2'
  meta: '>=0.9.0 <2.0.0'
