name: intl_translation_format
description: This package provides multiformat support for the Intl package
version: 1.0.0
homepage: https://github.com/jamesblasco/intl_translation_format
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl_generator: ^0.2.0+0
  intl_translation_arb: 
     git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_arb
      ref: null_safe #t-0.0.3
  intl_translation_xliff: 
    git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_xliff
      ref: null_safe #
  yaml: ^3.1.0
  test: ^1.15.1
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=4.0.0 < 4.4.0'
  args: '>=0.12.1 <2.3.0'
  meta: '>=0.9.0 <2.0.0'

dev_dependencies:
  analyzer: '>=0.36.0 <2.8.0'
  dart_style: ^2.1.1
  intl: '>=0.17.0 <0.20.0'
