name: intl_translation_format
description: This package provides multiformat support for the Intl package
version: 1.0.0
homepage: https://github.com/jamesblasco/intl_translation_format
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  intl_generator: ^0.4.0
  intl_translation_arb: 
    # path: /Users/stpu/Documents/work/extlibs/intl_translation_format/intl_translation_arb
     git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_arb
      ref: stefan_update-for-lingohub-changes-feb-2023
  intl_translation_xliff: 
    # path: /Users/stpu/Documents/work/extlibs/intl_translation_format/intl_translation_xliff
    git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_xliff
      ref: stefan_update-for-lingohub-changes-feb-2023
  yaml: ^3.1.0
  path: '>=0.9.0 <2.0.0'
  petitparser: ^5.0.0
  args: '>=0.12.1 <2.4.0'
  meta: '>=0.9.0 <2.0.0'

dev_dependencies:
  analyzer: ^5.0.0
  dart_style: ^2.1.1
  intl: '>=0.17.0 <0.20.0'
  flutter_lints: ^2.0.1
  test: ^1.15.1
