name: intl_translation_arb
description: Extract messages to arb files and generate translations from arb file
version: 1.0.0
homepage: https://github.com/jamesblasco/intl_translation_format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl_generator: ^0.2.0+0
  intl_translation_format:
     git: 
      url: git@github.com:Insight-Timer/intl_translation_format.git
      path: intl_translation_format
      ref: null_safe #it-0.0.3

dev_dependencies:
  analyzer: '>=0.36.0 <2.8.0'
  args: '>=0.12.1 <2.3.0'
  dart_style: ^2.1.1
  intl: '>=0.17.0 <0.20.0'
  path: '>=0.9.0 <2.0.0'
  petitparser: '>=4.0.0 <= 4.4.0'
  test: ^1.15.1
